config/routes.rb
MealsProject::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'
  resources :meals do
  	resources :comments
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :meal
end

app/models/meal.rb
class Meal < ActiveRecord::Base
	has_many :comments , dependent: :destroy
	validates :title, presence: true, length: {minimum: 5 }
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@meal = Meal.find(params[:meal_id])
		@comment = @meal.comments.create(params[:comment].permit(:body, :rating))
		redirect_to meal_path(@meal)
	end
	
	def destroy
	@meal = Meal.find(params[:meal_id])
	@comment = @meal.comments.find(params[:id])
	@comment.destroy
	redirect_to meal_path(@meal)
	
	end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

	def new
	@meal = Meal.new
	end
	
	def create
	
		@meal = Meal.new(params[:meal].permit(:title, :days, :number_ingrediants, :list_ingrediants))
	
		if @meal.save
		redirect_to @meal
		else
			render 'new'
		end
	end
	
	
	def show
		@meal = Meal.find(params[:id])
		
	end
	
	
	def index
		@meals = Meal.all
		
		
		
	end
	
	def edit
		@meal = Meal.find(params[:id])
	end
	
	def destroy
		@meal = Meal.find(params[:id])
		@meal.destroy
		
		redirect_to meals_path
	end
	
	def update
		@meal = Meal.find(params[:id])
		
		if @meal.update(params[:meal].permit(:title, :days, :number_ingrediants, :list_ingrediants))
			redirect_to @meal
		else
			render 'edit'
		end
	end
	
	
	
	
	private
		def meal_params
			params.require(:meal).permit(:title, :days, :number_ingrediants, :list_ingrediants)
	end
	
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_comment.html.erb
<%- model_class = Comment -%>
<p>
<dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= comment.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= comment.rating %></dd>





	<dd><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      [comment.meal, comment],
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %></dd>
      <br><br>    

app/views/comments/_form.html.erb
<%= form_for ([@meal, @meal.comments.build]), :html => { :class => 'form-horizontal' } do |f| %>
  
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :body, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :rating, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
   
    
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                meals_path, :class => 'btn' %>
  </div>
<% end %>
 
 

app/views/comments/edit.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:rating) %></th>
      <th><%= model_class.human_attribute_name(:body) %></th>
      <th><%= model_class.human_attribute_name(:meal_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= link_to comment.id, comment_path(comment) %></td>
        <td><%= comment.rating %></td>
        <td><%= comment.body %></td>
        <td><%= comment.meal_id %></td>
        <td><%=l comment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_comment_path(comment), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      comment_path(comment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_comment_path,
            :class => 'btn btn-primary' %>

app/views/comments/new.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<%- model_class = Comment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:rating) %>:</strong></dt>
  <dd><%= @comment.rating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @comment.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:meal_id) %>:</strong></dt>
  <dd><%= @comment.meal_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              comments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comment_path(@comment), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comment_path(@comment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MealsProject</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
	<div class="row">
		<div class="span9"><%= yield %></div>
		<div class="span3">
			
			<h2> About </h2>
			<p> Meals Database has been put together as a learning project and is very much work in progress. </p>
		</div>
	</div>
</div>

</body>
</html>

app/views/meals/_form.html.erb
<%= form_for @meal, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :days, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :days, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :list_ingrediants, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :list_ingrediants, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :number_ingrediants, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :number_ingrediants, :class => 'text_field' %>
    </div>
  </div>

 
  <div class="form-actions">
  <%= f.submit nil, :class => 'btn btn-primary' %>
 
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                meals_path, :class => 'btn' %>
  </div>
  
<% end %>

app/views/meals/edit.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/meals/index.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Meals Database</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "New Meal Entry", new_meal_path %></li>
          
        </ul>
      </div>
    </div>
  </div>
</div>





<%- model_class = Meal -%>
<div class="page-header">
  
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:days) %></th>
      <th><%= model_class.human_attribute_name(:list_ingrediants) %></th>
      <th><%= model_class.human_attribute_name("Comments/Rating") %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= link_to meal.title, meal_path(meal) %></td>
        <td><%= meal.days %></td>
        <td><%= meal.list_ingrediants %></td>
        <td>
          <table>
            <% meal.comments.each do |comment| %>
              <tr> 
                <td><%= comment.body %></td>
                <td><%= comment.rating %></td>
              </tr>
            <% end %>
          </table>
        </td>
        <td><%= meal.created_at.strftime("%d %b. %Y") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_meal_path(meal), :class => 'btn btn-mini' %>
        	<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      meal_path(meal),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
         
          <%= link_to t('.add', :default => t("helpers.links.add")),
          				meal_path(meal), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/meals/new.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/meals/show.html.erb
<%- model_class = Meal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @meal.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:days) %>:</strong></dt>
  <dd><%= @meal.days %></dd>
  <dt><strong><%= model_class.human_attribute_name(:list_ingrediants) %>:</strong></dt>
  <dd><%= @meal.list_ingrediants %></dd>
  <dt><strong><%= model_class.human_attribute_name(:number_ingrediants) %>:</strong></dt>
  <dd><%= @meal.number_ingrediants %></dd>
</dl>

<%- model_class = Comment -%>
<dl class="dl-horizontal">
	<dt><strong><%= model_class.human_attribute_name("comments") %>:</strong></dt>
	<br>
	<%= render @meal.comments %>
	<%= render :partial => 'comments/form' %>
</dl>




<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              meals_path, :class => 'btn'  %>
 
</div>

app/views/welcome/index.html.erb
<div class="hero-unit">
	
				<h1>Welcome to Meals Database</h1>
				<br>
				<br>
				
				<div class="btn btn-large btn-inverse"
				
				
				<%= link_to ""%>		
				
				<%= link_to "Get Started", controller: "meals", :class => "btn" %>
				
				</div>
		
			
		</div>
			
			
	